routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*----------Admin Route ---------- */ 

Route::get('admin/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\AdminLoginController@login')->name('admin.login');

/*---------------------------------*/

Route::get('admin/password-change',function(){
	return view('admin.email');
});
Route::get('admin/password-reset',function(){
	return view('admin.reset');
});
Route::get('admin/change-password',function(){
	return view('admin.changepassword');
});
Route::get('admin/dashboard',function(){
	return view('admin.dashboard');
});
Route::resource('admin/users', 'UserController',['except' => ['show']]);
Route::get('admin/dynamic-form',function(){
	return view('admin.dynamic-form.new');
});

Route::get('image/import',function(){
	return view('admin.image.index');
});
Route::get('admin/input',function(){
	return view('admin.input-type.index');
});
Route::get('/admin/input/form',function(){
	return view('admin.input-type.new');
});
Route::get('admin/data',['as'=>'admin.data.index','uses'=>'UserController@data']);

resources/views/admin/layout/alert.blade.php
@if(Session::has('message'))
	@if(Session::get('message_type'))
		<script>
	        $(document).ready(function(){
		        toastr.{{ Session::get('message_type') }}
		        ('{{ Session::get('message') }}');
	        });
	    </script>
    @endif
@endif

resources/views/admin/layout/breadcrumbs.blade.php
@if ($breadcrumbs)
    <ul class="breadcrumb p-0 m-0">
        @foreach ($breadcrumbs as $breadcrumb)
            @if(isset($breadcrumb->icon))
                {!! $breadcrumb->icon !!}
            @endif
            @if (!$loop->last)
                <li class="breadCrumbs_arrow"><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
            @else
                <li class="active">{{ $breadcrumb->title }}</li>
            @endif
        @endforeach
    </ul>
@endif

resources/views/admin/layout/footer.blade.php
<?=Html::script('backend/js/jquery.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/bootstrap.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/jquery.slimscroll.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/toastr-master/toastr.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/pace.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/main.js', [], IS_SECURE)?>
<?=Html::script('js/parsley.js', [], IS_SECURE)?>
@yield('script')

resources/views/admin/layout/header.blade.php
<header class="main-header hidden-print">
	<a class="logo" href="/admin/dashboard">
        <p class="large">
         	<img src="<?= asset('backend/images/admin.png') ?>">
        </p>
        <p class="small"></p>
    </a>
    <a class="sidebar-toggle" data-toggle="offcanvas"></a>
        @yield('top_fixed_content')
</header>

resources/views/admin/layout/layout.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#ffffff">
        <title>Admin</title>
        <!--  Css files  -->
        @include('admin.layout.web_header')
        @yield('style')
    </head>
    <body class="sidebar-mini fixed">
        <div class="wrapper">
            @yield('start_form')
            <!-- Header file -->
            @include('admin.layout.header')
            <!-- Side-Bar-->
            @include('admin.layout.sidebar')
            <!-- Content Start here -->
            <div class="content-wrapper">
                @yield('content')
            </div>
            <!-- Content End here -->
            <!-- footer contant -->
            @yield('end_form')
        </div>
        <!-- Js file -->
        @include('admin.layout.footer')
    </body>
</html>

resources/views/admin/layout/overlay.blade.php
<div class="overlay" style="display:none">
    <div class="m-loader mr-20"></div>
</div>

resources/views/admin/layout/sidebar.blade.php
<aside class="main-sidebar hidden-print">
    <section class="sidebar">
        <div class="search-panel">
            <div class="search-box">
              <div class="icon pull-left"><i class="fa fa-search"></i></div>
              <input class="text" type="text" placeholder="Special Search if require">
              <div class="clearfix"></div>
            </div>
        </div>
        <!-- Sidebar Menu-->
         <div class="sidebar-content">
            <ul class="sidebar-menu" id="nav-accordion">
                <ul class="sidebar-menu" id="nav-accordion">
                <li class=" @if(Request::segment(2) == 'dashboard') active @endif">
                    <a href="/admin/dashboard">
                    <i class="fa fa-dashboard"></i>
                    <span>Dashboard</span>
                    </a>
                </li>
                <li class=" @if(Request::segment(2) == 'users') active @endif">
                    <a href="<?=route('users.index',['type'=>'active'])?>">
                    <i class="fa fa-user"></i>
                    <span>Users</span>
                    </a>
                </li>
                <li class=" @if(Request::segment(2) == 'dynamic-form') active @endif">
                    <a href="/admin/dynamic-form">
                    <i class="fa fa-user"></i>
                    <span>Dynamic-form</span>
                    </a>
                </li>
                <li class=" @if(Request::segment(2) == 'import') active @endif">
                    <a href="/image/import">
                    <i class="fa fa-file"></i>
                    <span>Import</span>
                    </a>
                </li>
                <li class=" @if(Request::segment(2) == 'input') active @endif">
                    <a href="/admin/input">
                    <i class="fa fa-user"></i>
                    <span>Input type</span>
                    </a>
                </li>
                <li class="sub-menu @if(Request::segment(2) == 'master') active @endif">
                    <a href="javascript:;">
                        <i class="fa fa-bars"></i>
                        <span>Menu</span>
                        <i class="fa fa-angle-right"></i>
                    </a>
                    <ul class="treeview-menu @if(Request::segment(2) == 'master') menu-open @endif">
                        <li>
                            <a href="" class="@if(Request::segment(3) == 'events') active @endif">
                                <i class="fa fa-bars"></i>
                                <span>sub menu</span>
                                <i class="fa fa-angle-right"></i>
                            </a>
                            <ul class="treeview-menu @if(Request::segment(2) == 'master') menu-open @endif">
                                <li>
                                    <a href="" class="@if(Request::segment(3) == 'events') active @endif">
                                        <i class="fa fa-bars"></i>
                                        <span>tree menu</span>
                                    </a>
                                </li>
                            
                            </ul>
                        </li>
                        
                    </ul>
                </li>
                
                </ul>
                <li class="spacer"></li>
                <li class="logout">
                    <a href="javascript:;">
                        <i class="fa fa-user"></i>
                        <span>Admin</span>
                        <i class="fa fa-angle-right"></i>
                    </a>
                    <ul class="logout-modal">
                        <li>
                            <a href="/admin/change-password">Change Password</a>
                        </li>
                        <li>
                            <a href="/admin/login">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </section>
</aside>

resources/views/admin/layout/web_header.blade.php
<?=Html::style('backend/css/main.css')?>
<?=Html::style('css/parsley.css')?>
<?=Html::style('backend/plugins/toastr-master/toastr.min.css')?>